### ISSUE TITLE
Any XML file that contains methods defined internally by rakudo will cause an exception.

### ISSUE THREAD

**Issue by Xliff** [MARTIMM/XmlActions#1]
Take the following excerpt for an example:

```
  <complexType name="ShipsFromType">
    <all>
      <element name="State" type="string" minOccurs="0"/>
      <element name="Country" type="string" minOccurs="0"/>
    </all>
  </complexType>
```

This will trip up XML::Actions with the following error, because method all() is provided by Any:

```
Too many positionals passed; expected 1 argument but got 2
  in method check-action at /home/cbwood/Other Projects/XmlActions/lib/XML/Actions.pm6 (XML::Actions) line 124
  in block  at /home/cbwood/Other Projects/XmlActions/lib/XML/Actions.pm6 (XML::Actions) line 79
  in method process-node at /home/cbwood/Other Projects/XmlActions/lib/XML/Actions.pm6 (XML::Actions) line 76
  in block  at /home/cbwood/Other Projects/XmlActions/lib/XML/Actions.pm6 (XML::Actions) line 79
  in method process-node at /home/cbwood/Other Projects/XmlActions/lib/XML/Actions.pm6 (XML::Actions) line 76
  in block  at /home/cbwood/Other Projects/XmlActions/lib/XML/Actions.pm6 (XML::Actions) line 79
  in method process-node at /home/cbwood/Other Projects/XmlActions/lib/XML/Actions.pm6 (XML::Actions) line 78
  in method process-document at /home/cbwood/Other Projects/XmlActions/lib/XML/Actions.pm6 (XML::Actions) line 72
  in method process at /home/cbwood/Other Projects/XmlActions/lib/XML/Actions.pm6 (XML::Actions) line 58
  in sub MAIN at project-tools/test-parse-1.pl6 line 132
  in block <unit> at project-tools/test-parse-1.pl6 line 9
```

This will find [this method](https://github.com/rakudo/rakudo/blob/master/src/core.c/Any.pm6#L400), which does not have the required number of parameters.

In such a situation, I'm not sure of the best way to fix it. For now however, I would suggest an error message that details the issue.

```
Method {$a} has triggered an error. If this method is not in your XML::Actions class, then you should consider overwriting it with the proper signature.
```

See [this discussion](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-09-12#l688) for details.

**Comment by MARTIMM** [comment]
Ik can reproduce the problem. I think that the solution will not be easy...

**Comment by MARTIMM** [comment]
A shortcut solution is to provide a `method all ( Array $parent-path, ... ) { }` in the class given to `XML::Actions.process()` to prevent the crash.

I can add an extra test for the method name extended with '-START' as I've done with testing for the end tag '-END'. Then add a deprecation message to the previous one. This will not break backward compatibility but provides a way to change things. In this deprecation phase, you still need to add a method 'all()' until this way of calling is removed.

For me of course, it is easier to keep it the way it was and make some document notes. The above idea makes it more bullet proof.

What do you think?

**Comment by Xliff** [comment]
Sounds like a good compromise for the situation. I will add an override for all.

Thanks!

**Comment by MARTIMM** [comment]
After studying extended identifiers I come up with the names `element:start()` and `element:end()`. This looks much nicer and XML namespace names do not interfere.
 I also change the names for processing PI, CDATA, TEXT and COMMENT. See README in next version.
